// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "JawClamp.h"
#include "../RobotMap.h"
#include "../Commands/JawClamp/CloseClaw.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

JawClamp::JawClamp() : frc::Subsystem("JawClamp") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    right = RobotMap::clawClampRight;
    left = RobotMap::clawClampLeft;
    cronch = RobotMap::clawCronch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void JawClamp::InitDefaultCommand() {
    // Set the default command for a subsystem here.
	SetDefaultCommand(new CloseClaw());
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void JawClamp::Periodic() {

    // Put code here to be run every loop

}

void JawClamp::setForward(){
	right->Set(DoubleSolenoid::Value::kForward);
	left->Set(DoubleSolenoid::Value::kForward);
}

void JawClamp::setBack(){
	right->Set(DoubleSolenoid::Value::kReverse);
	left->Set(DoubleSolenoid::Value::kReverse);
}

void JawClamp::stop(){
	right->Set(DoubleSolenoid::Value::kOff);
	left->Set(DoubleSolenoid::Value::kOff);
}

void JawClamp::pushCronch(){

	cronch->Set(frc::DoubleSolenoid::Value::kReverse);
}

void JawClamp::releaseCronch(){

	cronch->Set(frc::DoubleSolenoid::Value::kForward);

}

// Put methods for controlling this subsystem
// here. Call these from Commands.

