// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/JawClamp/OpenClaw.h"
#include "Commands/JawClamp/ToggleCronch.h"
#include "Commands/JawLift/LowerClaw.h"
#include "Commands/Succ/Spit.h"
#include "Commands/Succ/Eat.h"
#include "Commands/Succ/Shoot.h"


// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystick1.reset(new frc::Joystick(0));

    butt1.reset(new frc::JoystickButton(joystick1.get(),1));
    butt1->WhileHeld(new OpenClaw());

    butt2.reset(new frc::JoystickButton(joystick1.get(),2));
    butt2->WhileHeld(new LowerClaw());

    butt3.reset(new frc::JoystickButton(joystick1.get(),3));
    //butt3->WhileHeld(new SuccIn());
    //butt3->WhenReleased(new StopSucc());
    butt4.reset(new frc::JoystickButton(joystick1.get(),4));
    //butt4->WhileHeld(new LiftClaw());
    butt5.reset(new frc::JoystickButton(joystick1.get(),5));
    butt5->WhenReleased(new Shoot());
    //butt5->WhileHeld(new SuccOut());
    //butt5->WhenReleased(new StopSucc());
    butt6.reset(new frc::JoystickButton(joystick1.get(), 6));
    butt6->ToggleWhenPressed(new ToggleCronch());
    butt10.reset(new frc::JoystickButton(joystick1.get(),10));
    butt10->WhileHeld(new Spit());
    
    //butt10 is out
    butt11.reset(new frc::JoystickButton(joystick1.get(),11));
    butt11->WhileHeld(new Eat());

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getJoystick1() {
   return joystick1;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
